server:
  port: 8002

#http://localhost:8000
eureka:
  client:
    healthcheck:
      #这里是否需要开启健康检查   ,答:可以不开启     开启健康检查（需要spring-boot-starter-actuator依赖）
      enabled: true
    #是否可检索
    fetch-registry: true
    #是否注册到eureka服务器
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://172.16.12.2:8000/eureka/
  instance:
    # 默认30s，表示eureka client发送心跳给server端的频率
    lease-renewal-interval-in-seconds: 10
    # 默认90s，表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 30

crawl:
  type: 4

spring:
  application:
    name: ivma-appvideo-crawl${crawl.type}
  thymeleaf:
    cache: false

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@(description=(address_list= (address=(host=172.16.24.75)(protocol=tcp)(port=1521))(address=(host=172.16.24.76)(protocol=tcp) (port=1521)) (load_balance=yes)(failover=on))(connect_data=(service_name= orcl)))
    url: jdbc:oracle:thin:@172.16.39.212:1521:rac2
    username: ivma
    password: ivma

  kafka:
    bootstrap-servers: 172.16.12.12:9092
  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: 172.16.12.12:9092
          zk-nodes: 172.16.12.11:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        output:
          destination: ${kafka.topic}
          content-type: text/plain
          producer:
            # 输出消息分布到3个分区
            partitionCount: 1
            #partitionKeyExtractorClass: org.springframework.cloud.stream.partitioning.CustomPartitionKeyExtractorClass
            #partitionSelectorClass: org.springframework.cloud.stream.partitioning.CustomPartitionSelectorClass
            headerMode: raw
            bufferSize: 16384
            maxRequestSize: 1048576
            sync: true
            batchTimeout: 0

kafka:
  topic: appvideo

mybatis:
  #实体类的包路径
  type-aliases-package: com.certus.ivma.entity
  #扫描classpath下mapper目录下的所有.xml文件
  mapper-locations: classpath:mapper/*.xml

logging:
  path: D:/rome/
  file: springbootdemo.log
  #TARCE < DEBUG < INFO 默认 < WARN < ERROR < FATAL
  level:
    root: INFO
    com:
      certus:
        ivma:
          mapper: DEBUG # 打印sql

#spring线程池
thread_pool:
  schedule_executor:
    core_pool_size: 5
    max_pool_size: 5
    queue_capacity: 0
    name_prefix: schedule-executor-
    keep_alive_seconds: 10
  execute_executor:
    core_pool_size: 5
    max_pool_size: 500
    queue_capacity: 0
    name_prefix: execute-executor-
    keep_alive_seconds: 10

app:
  shell:
    path: http://localhost:80

constants:
  task:
    execute:
      max:
        second: 60
  host:
    keepalive:
      second: 60
