server:
  port: 8002

#http://localhost:8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.12.2:8000/eureka/
crawl:
  type: 4

spring:
  application:
    name: ivma-appvideo-crawl${crawl.type}
  thymeleaf:
    cache: false

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@(description=(address_list= (address=(host=172.16.24.75)(protocol=tcp)(port=1521))(address=(host=172.16.24.76)(protocol=tcp) (port=1521)) (load_balance=yes)(failover=on))(connect_data=(service_name= orcl)))
    url: jdbc:oracle:thin:@172.16.39.212:1521:rac2
    username: ivma
    password: ivma

  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.12.12:9092
          zk-nodes: 172.16.12.11:2182
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        output:
          destination: appvideo
          content-type: text/plain
          producer:
            partitionCount: 1
            partitionKeyExtractorClass: org.springframework.cloud.stream.partitioning.CustomPartitionKeyExtractorClass
            partitionSelectorClass: org.springframework.cloud.stream.partitioning.CustomPartitionSelectorClass
            headerMode: raw
            bufferSize: 16384
            maxRequestSize: 1048576
            sync: true
            batchTimeout: 0

kafka:
  topic: appvideo

mybatis:
  #实体类的包路径
  type-aliases-package: com.certus.ivma.entity
  #扫描classpath下mapper目录下的所有.xml文件
  mapper-locations: classpath:mapper/*.xml

logging:
  path: D:/rome/
  file: springbootdemo.log
  #TARCE < DEBUG < INFO 默认 < WARN < ERROR < FATAL
  level:
    root: INFO
    com:
      certus:
        ivma:
          mapper: DEBUG # 打印sql

#spring线程池
thread_pool:
  schedule_executor:
    core_pool_size: 5
    max_pool_size: 5
    queue_capacity: 0
    name_prefix: schedule-executor-
    keep_alive_seconds: 10
  execute_executor:
    core_pool_size: 5
    max_pool_size: 500
    queue_capacity: 0
    name_prefix: execute-executor-
    keep_alive_seconds: 10

app:
  shell:
    path: http://localhost:80

constants:
  task:
    execute:
      max:
        second: 60
  host:
    keepalive:
      second: 60
