server:
  port: 8005

#http://localhost:8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
receive:
  type: 4
  
spring:
  application:
    name: ivma-appvideo-receive${receive.type}
  thymeleaf:
    cache: false

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@(description=(address_list= (address=(host=172.16.24.75)(protocol=tcp)(port=1521))(address=(host=172.16.24.76)(protocol=tcp) (port=1521)) (load_balance=yes)(failover=on))(connect_data=(service_name= orcl)))
    url: jdbc:oracle:thin:@172.16.39.212:1521:rac2
    username: ivma
    password: ivma
    
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: admin
  
  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: 172.16.12.7:9092
          zk-nodes: 172.16.12.5:2182
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        sourceA:
          destination: test_spring_stream
          content-type: text/plain
          producer:
            partitionCount: 1

mybatis:
  #实体类的包路径
  type-aliases-package: com.certus.ivma.entity
  #扫描classpath下mapper目录下的所有.xml文件
  mapper-locations: classpath:mapper/*.xml

logging:
  path: D:/rome/
  file: springbootdemo.log
  #TARCE < DEBUG < INFO 默认 < WARN < ERROR < FATAL
  level:
    root: INFO
    com:
      certus:
        ivma:
          mapper: DEBUG # 打印sql

#spring线程池
thread_pool:
  schedule_executor:
    core_pool_size: 5
    max_pool_size: 5
    queue_capacity: 0
    name_prefix: schedule-executor-
    keep_alive_seconds: 10
  execute_executor:
    core_pool_size: 5
    max_pool_size: 500
    queue_capacity: 0
    name_prefix: execute-executor-
    keep_alive_seconds: 10
  
app:
  shell:
    path: http://localhost:80

constants:
  task:
    execute:
      max:
        second: 60
  host:
    keepalive:
        second: 60
